pusher:
  wss_host: '127.0.0.1'
  wss_port: 8080
  api_host: '127.0.0.1'
  api_port: 4567
  host: '127.0.0.1'
  sockjs_host: '127.0.0.1'
  ws_port: 3004
  app_id: '1'
  app_key: 'c46c644b78f84661ace01b35dffceabc'
  app_secret: '15c85d0ce00c492888423aca73f65d19'

mailer:
  address: 'smtp.gmail.com'
  port: 587
  domain: 'mail.google.com'
  user_name: 'emailfaceit@gmail.com'
  password: 'hiddenfile'
  authentication: :plain
  enable_starttls_auto: true